apiVersion: v1
kind: page
spec:
  id: y6gRWAM
  title: editProfile
  display: shell
  content:
    - component: PageRow
      name: pageRow2
      props:
        justifyContent: start
      children:
        - component: Form
          name: form
          props:
            onSubmit:
              $$jsExpressionAction: updateProfile.call() && getTrainerProfile.refetch()
            formControlsAlign: start
            submitButtonText: Update
            formControlsFullWidth: false
            hasResetButton: false
          layout:
            columnSize: 1
          children:
            - component: Text
              name: fullName
              props:
                value: "Full Name:"
                variant: body1
            - component: TextField
              name: textField
              props:
                defaultValue:
                  $$jsExpression: |
                    getTrainerProfile.data[0].full_name
                name: full_name
                minLength: 3
                isInvalid: false
                disabled: false
            - component: Text
              name: website
              props:
                value: "Website:"
            - component: TextField
              name: textField1
              props:
                defaultValue:
                  $$jsExpression: |
                    getTrainerProfile.data[0].website
                label: ""
                name: website
                isInvalid:
                  $$jsExpression: |
                    !/^(ftp|http|https):\/\/[^ "]+$/.test(textField1.value)
        - component: Form
          name: form1
          props:
            formControlsAlign: start
            onSubmit:
              $$jsExpressionAction: updateAvatar.call() && getAvatarUrl.refetch()
            formControlsFullWidth: false
          children:
            - component: Text
              name: text
              props:
                value: "Avatar:"
            - component: PageRow
              name: pageRow1
              props:
                justifyContent: start
              children:
                - component: PageColumn
                  name: pageColumn
                  layout:
                    columnSize: 1
                  children:
                    - component: Image
                      name: image
                      layout:
                        horizontalAlign: start
                        verticalAlign: center
                      props:
                        src:
                          $$jsExpression: |
                            getAvatarUrl.data.publicUrl
                        height: 100
                        width: 100
                    - component: FilePicker
                      name: filePicker
                      layout:
                        columnSize: 1
                      props:
                        multiple: false
                        isRequired: false
                        name: avatar_url
                        label: ""
  queries:
    - name: getAvatarUrl
      query:
        function: trainers.ts#getAvatarPublicUrl
        kind: local
      parameters:
        - name: path
          value:
            $$jsExpression: |
              getTrainerProfile.data[0].avatar_url
    - name: getTrainerProfile
      query:
        function: trainers.ts#getTrainerProfile
        kind: local
      parameters:
        - name: email
          value:
            $$jsExpression: |
              ""
        - name: password
          value:
            $$jsExpression: |
              ""
    - name: updateProfile
      query:
        kind: local
        function: trainers.ts#updateTrainerProfile
      parameters:
        - name: email
          value:
            $$jsExpression: |
              ""
        - name: password
          value:
            $$jsExpression: |
              ""
        - name: full_name
          value:
            $$jsExpression: |
              textField.value
        - name: website
          value:
            $$jsExpression: |
              textField1.value
      mode: mutation
    - name: updateAvatar
      query:
        function: trainers.ts#updateAvatar
        kind: local
      parameters:
        - name: base64
          value:
            $$jsExpression: |
              filePicker.value[0].base64
      mode: mutation
